### ISSUE TITLE
Inspecting stashes in the watch window shows nothing

### ISSUE THREAD

**Issue by brummett** [brummett/Devel-hdb#61]
Putting %main:: (or any other package) in the watch window shows nothing for its value

**Comment by stphnlyd** [comment]
I looked at this a little bit. I think there are a couple of issues related to this.

In Devel::hdb it would expect __refaddr from from the value from Data::Transform::ExplicitMetadata. But according to https://metacpan.org/source/BRUMMETT/Data-Transform-ExplicitMetadata-0.06/lib/Data/Transform/ExplicitMetadata.pm#L75 for GLOB values it deletes __refaddr in this case. I think this logic in Data::Transform::ExplicitMetadata is correct as you deliberately encode a GLOB's reference, that reference is created only at that place so its reference address is meaningless. So IMHO in perlvalue.js you should allow values with no __refaddr. 

In Data::Transform::ExplicitMetadata there's another problem. When you do takes the reference from a  GLOB https://metacpan.org/source/BRUMMETT/Data-Transform-ExplicitMetadata-0.06/lib/Data/Transform/ExplicitMetadata.pm#L74, this reference would stringify to like GLOB(0x???????). And because this reference is like temporary and is used as a parameter in another call to encode(), it could be that all GLOB values in %main:: end up to get the same reference address in encode(). And because of the duplication in the GLOB(0x???????) values, it would mistakenly make them __recursive=1, and thus lose info of all GLOBs except the first one processed by encode(). To see this you can try below (I tried it under Perl 5.20.)
```
my $json = JSON->new->pretty(1)->canonical(1);
print $json->encode(encode(\%main::));
```
I just tried adding a 4th parameter in encode() for overriding the key used by %$seen, but I then found that it gets all namespace data in a hierarchical manner, that is too huge. I wonder if we should just simply make it behave like Data::Dumper that just displays a GLOB as a simple string, or we should limit the number of layers that are expanded/evaluated.

**Comment by brummett** [comment]
You were right on both points.  This fixed the serialization problem: https://github.com/brummett/Data-Transform-ExplicitMetadata/pull/16/commits/f921fdb2c8b6d6af02b885b6391e846433ee17bd
It's merged into master in that repo.

And #116 fixes the refaddr problem in perlvalue.js.

I'll get new releases uploaded to CPAN in the next couple of days.

Thanks for looking into it!

**Comment by stphnlyd** [comment]
@brummett Thanks. But before you release a new Devel::hdb to CPAN I would like to contribution/discuss a couple of other issues. Too busy recently but I will try to update within this week.
